### ISSUE TITLE
Species

### ISSUE THREAD

**Issue by sarevalo7** [jonchang/fishtree#4]
I'm trying to retrieve the phylogeny of two different fish species (minnows) for comparison using the following code but it causes an error: 

>cyp <- fishtree_phylogeny(species= "Scientific name1, Scientific name2") 
Error: Must include at least 2 tips in 'species'. 

I'm fairly new to this so any help would be great!

**Comment by jonchang** [comment]
@sarevalo7 `species` should be a vector, so: `fishtree_phylogeny(species = c("Species 1", "Species 2"))`. I will look into adding an example for this case. See https://r4ds.had.co.nz/vectors.html for an introduction to this topic.

**Comment by jonchang** [comment]
6005d87

**Comment by sarevalo7** [comment]
I feel dumb. Thank you, kindly! Hopefully didn't take up too much of your
time.
